language: c

compiler:
  - gcc
  - clang

os:
  - linux

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

services: mongodb

env:
  - CFLAGS="$CFLAGS -Werror -Wno-cast-align"

addons:
  apt:
    packages:
      - gdb

script:
  - sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts'
  - ulimit -a
  - ulimit -c unlimited || true
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_MAINTAINER_FLAGS=ON -ENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .
  - make -j 8
  - make check


after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gdb; fi
  - find /cores . -name \*core\* -exec ./.travis.scripts/debug-core.sh {} \;

# Exclude gcc on osx since it's just an alias for clang.
matrix:
  include:
  - compiler: gcc
    os: linux-ppc64le
    addons:
      apt:
        packages:
        - mongodb-enterprise
        - gdb
        sources:
        - sourceline: 'deb http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/4.0 multiverse'
          key_url: 'https://www.mongodb.org/static/pgp/server-4.0.asc'
        update: true
    services:
    before_install:
    - sudo systemctl start mongod
  - compiler: clang
    os: osx
    services:
    before_script:
      - brew update
      # https://github.com/Homebrew/homebrew-core/issues/26358
      - brew unlink python
      # "brew install" can succeed but return 1 if it has "caveats".
      - brew tap mongodb/brew && brew install mongodb-community || true
      - brew services start mongodb-community

git:
  depth: 20
